[build]
  command = "cd document-manager && npm install --legacy-peer-deps && npm run build --prod"
  publish = "dist/document-manager"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
